In [1]:
import gym

Initializing Environments

In [ ]:
env = gym.make("LunarLander-v2", render_mode="human")
print(env.unwrapped)

env.action_space.seed(42)
observation, info = env.reset(seed=42)

for _ in range(10000):
    observation, reward, terminated, info = env.step(env.action_space.sample())

    if terminated or truncated:
        observation, info = env.reset()
env.close()

TypeError: __init__() got an unexpected keyword argument 'render_mode'

Space

In [2]:
import numpy as np
from gym.spaces import Box, Discrete, Dict, Tuple, MultiBinary, MultiDiscrete

In [5]:
observation_space = Box(low=-1.0, high=2.0, shape=(3,), dtype=np.float32)
print(observation_space.sample())

observation_space = Discrete(4)
print(observation_space.sample())

observation_space = Discrete(5, start=-2)
print(observation_space.sample())

observation_space = Dict({"position": Discrete(2), "velocity": Discrete(3)})
print(observation_space.sample())

observation_space = Tuple((Discrete(2), Discrete(3)))
print(observation_space.sample())

observation_space = MultiBinary(5)
print(observation_space.sample())

observation_space = MultiDiscrete([5, 2, 2])
print(observation_space.sample())

[-0.66276455 -0.43569604 -0.09883118]
3
1
OrderedDict([('position', 1), ('velocity', 1)])
(0, 2)
[0 0 1 1 1]
[4 1 1]


Wrappers

In [4]:
from gym.wrappers import RescaleAction

In [10]:
base_env = gym.make("BipedalWalker-v3")
base_env.action_space

Box(-1.0, 1.0, (4,), float32)

In [11]:
wrapped_env = RescaleAction(base_env, min_action=0, max_action=1)
wrapped_env.action_space

Box(0.0, 1.0, (4,), float32)

In [12]:
wrapped_env

<RescaleAction<TimeLimit<OrderEnforcing<PassiveEnvChecker<BipedalWalker<BipedalWalker-v3>>>>>>

Playing within an Environment

In [13]:
from gym.utils.play import play

In [23]:
play(gym.make('Pong-v1'))

NameNotFound: Environment Pong doesn't exist. 

In [37]:
import pygame
from gym.utils.play import play, PlayPlot

In [38]:
mapping = {(pygame.K_LEFT,): 0, (pygame.K_RIGHT,): 1}
play(gym.make("CartPole-v0", render_mode="rgb_array"), keys_to_action=mapping)

In [39]:
def callback(obs_t, obs_tp1, action, rew, done, info):
    return [rew,]

In [40]:
plotter = PlayPlot(callback, 30*5, ["reward"])
env = gym.make("Pong-v0")
play(env, callback=plotter.callback)

NameNotFound: Environment Pong doesn't exist. 

In [36]:
gym.envs.registry.keys()

dict_keys(['CartPole-v0', 'CartPole-v1', 'MountainCar-v0', 'MountainCarContinuous-v0', 'Pendulum-v1', 'Acrobot-v1', 'LunarLander-v2', 'LunarLanderContinuous-v2', 'BipedalWalker-v3', 'BipedalWalkerHardcore-v3', 'CarRacing-v2', 'Blackjack-v1', 'FrozenLake-v1', 'FrozenLake8x8-v1', 'CliffWalking-v0', 'Taxi-v3', 'Reacher-v2', 'Reacher-v4', 'Pusher-v2', 'Pusher-v4', 'InvertedPendulum-v2', 'InvertedPendulum-v4', 'InvertedDoublePendulum-v2', 'InvertedDoublePendulum-v4', 'HalfCheetah-v2', 'HalfCheetah-v3', 'HalfCheetah-v4', 'Hopper-v2', 'Hopper-v3', 'Hopper-v4', 'Swimmer-v2', 'Swimmer-v3', 'Swimmer-v4', 'Walker2d-v2', 'Walker2d-v3', 'Walker2d-v4', 'Ant-v2', 'Ant-v3', 'Ant-v4', 'Humanoid-v2', 'Humanoid-v3', 'Humanoid-v4', 'HumanoidStandup-v2', 'HumanoidStandup-v4'])